# -*- coding: utf-8 -*-
"""EDA Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLEqiwDMKPvzBhz7-wwTUNUUb6Pel78O

# **Course Project Guidelines**


### Evaluation Criteria

Your submission will be evaluated using the following criteria:

* Dataset must contain at least 3 columns and 150 rows of data
* You must ask and answer at least 5 questions about the dataset
* Your submission must include at least 5 visualizations (graphs)
* Your submission must include explanations using markdown cells, apart from the code.
* Your work must not be plagiarized i.e. copy-pasted for somewhere else.


Follow this step-by-step guide to work on your project.


### Step 1: Select a real-world dataset

- Find an interesting dataset on this page: https://www.kaggle.com/datasets?fileType=csv
- The data should be in CSV format, and should contain at least 3 columns and 150 rows
- Download the dataset using the [`opendatasets` Python library](https://github.com/JovianML/opendatasets#opendatasets)

Here's some sample code for downloading the [US Elections Dataset](https://www.kaggle.com/tunguz/us-elections-dataset):

```
import opendatasets as od
dataset_url = 'https://www.kaggle.com/tunguz/us-elections-dataset'
od.download('https://www.kaggle.com/tunguz/us-elections-dataset')
```

**Libraries Used**
* Pandas (import pandas as pd)  for data loading, cleaning, filtering, grouping, and analysis.
* NumPy (import numpy as np) for numerical calculations and statistical operations.
* Matplotlib (import matplotlib.pyplot as plt)  for creating charts and graphs.
* Seaborn (import seaborn as sns) for advanced data visualizations.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""**Library Used:**
***Pandas***
* pd.read_csv() to read the CSV file.
* head() to preview the data.
"""

prod_df=pd.read_csv("/content/prod.csv")
prod_df.info()

prod_df

"""Pandas:
shape attribute was used to determine the number of rows and columns in the dataset
"""

prod_df.shape

"""Pandas:
describe() method was used to calculate statistical measures automatically
"""

prod_df.describe()

"""### Step 2: Perform data preparation & cleaning

- Load the dataset into a data frame using Pandas
- Explore the number of rows & columns, ranges of values etc.
- Handle missing, incorrect and invalid data
- Perform any additional steps (parsing dates, creating additional columns, merging multiple dataset etc.)

The prod_df.isnull().sum() statement returns the number of missing values present in every column of the dataset. This helps identify columns that may require cleaning, such as filling missing values or removing incomplete records.Panda library function used here
"""

#daily_social_media_time,perceived_productivity_score, actual_productivity_score
#stress_level,sleep_hours,screen_time_before_sleep,job_satisfaction_score have some null values
prod_df.isnull().sum()

"""**Handled missing** values in multiple numerical columns by replacing them with their respective mean values. After filling the missing values, I verified that no null values remained in those columns.

*Columns Cleaned*
* daily_social_media_time
* perceived_productivity_score
* actual_productivity_score
* stress_level
* sleep_hours
* screen_time_before_sleep
* job_satisfaction_score
*Library Used*

*Pandas*
* fillna() was used to replace missing values.
mean() was used to calculate the average value of each column.
* isnull().sum() was used to verify that all missing values had been handled.
"""

prod_df["daily_social_media_time"]=prod_df["daily_social_media_time"].fillna(prod_df["daily_social_media_time"].mean())
prod_df["daily_social_media_time"].isnull().sum()

prod_df["perceived_productivity_score"]=prod_df["perceived_productivity_score"].fillna(prod_df["perceived_productivity_score"].mean())
prod_df["perceived_productivity_score"].isnull().sum()

prod_df["actual_productivity_score"]=prod_df["actual_productivity_score"].fillna(prod_df["actual_productivity_score"].mean())
prod_df["actual_productivity_score"].isnull().sum()

prod_df["stress_level"]=prod_df["stress_level"].fillna(prod_df["stress_level"].mean())
prod_df["stress_level"].isnull().sum()

prod_df["sleep_hours"]=prod_df["sleep_hours"].fillna(prod_df["sleep_hours"].mean())
prod_df["sleep_hours"].isnull().sum()

prod_df["screen_time_before_sleep"]=prod_df["screen_time_before_sleep"].fillna(prod_df["screen_time_before_sleep"].mean())
prod_df["screen_time_before_sleep"].isnull().sum()

prod_df["job_satisfaction_score"]=prod_df["job_satisfaction_score"].fillna(prod_df["job_satisfaction_score"].mean())
prod_df["job_satisfaction_score"].isnull().sum()

"""**The prod_df.info()** function that is also a panda library function  provides important information about the dataset, including:

Total number of rows and columns.
Column names.
* Data types of each column (int, float, object, etc.).
* Number of non-null values in each column.
* Memory usage of the dataset.
"""

prod_df.info()

"""Checked the dataset for duplicate records using duplicated().sum() to identify any repeated rows that might affect the analysis."""

#No duplicates found
prod_df.duplicated().sum()

"""### Step 3: Perform exploratory analysis & visualization


"""

#Compute the mean, sum, range and other interesting statistics for numeric columns
prod_df.describe()

"""**What I Did**: Calculated the range of each numerical column by subtracting the minimum value from the maximum value to measure the spread of data.

**Library Used**: Pandas and NumPy – select_dtypes(include=np.number) was used to select numerical columns, while max() and min() were used to calculate the range for each column.

**Purpose**: This helped identify how widely the values vary in each numerical feature and provided insights into the distribution and variability of the data.
"""

# find range for each numeric column
numeric_df = prod_df.select_dtypes(include=np.number)
column_ranges = numeric_df.max() - numeric_df.min()
print("Ranges for numeric columns:")
print(column_ranges)

"""**What I Did**

Created a histogram to visualize the distribution of the daily_social_media_time variable and understand how much time individuals spend on social media each day.

***Libraries Used***
* Matplotlib (plt.hist()) – to create the histogram.
* Seaborn (sns.set_style()) – to improve the appearance of the plot.
***Visualization Interpretation***


* The histogram shows that most individuals spend between 1 and 5 hours per day on social media.
* The highest frequency is observed around 2–4 hours, indicating that this is the most common range of social media usage.
* As daily social media time increases beyond 5 hours, the number of individuals decreases significantly.
* A small number of users spend more than 10 hours per day on social media, which appear as extreme values or potential outliers.
* The distribution is right-skewed (positively skewed) because most observations are concentrated at lower values while a long tail extends toward higher values.



***Key Insight***

The majority of people in the dataset are moderate social media users, spending only a few hours daily, while heavy social media usage is relatively uncommon. This suggests that typical daily social media consumption is concentrated in the lower range of the dataset.
"""

#Distribution of age using Histogram
plt.hist(prod_df.daily_social_media_time,color='purple')
sns.set_style("darkgrid")
plt.title("Distribution of daily_social_media_time")
plt.xlabel("daily_social_media_time")
plt.ylabel("Frequency")

"""**The value_counts()** function returns the total number of users who prefer each social media platform. This helps compare the popularity of different platforms within the dataset.

This **analysis** reveals the distribution of social media platform preferences and helps determine which platform is used the most by the individuals in the dataset.
"""

social_prefer=prod_df["social_platform_preference"].value_counts()
social_prefer

"""**What I Did**

Created a pie chart to visualize the distribution of users' preferred social media platforms and compare their popularity.

***Libraries Used***

*Matplotlib*

* plt.pie() was used to create the pie chart.
* labels displayed the platform names.
* autopct='%1.1f%%' displayed the percentage share of each platform.
* plt.title() added a title to the chart.
***Visualization Interpretation***
* The pie chart shows that the usage of social media platforms is almost evenly distributed among users.
* TikTok has the highest share with approximately 20.3% of users.
* Facebook has the lowest share with approximately 19.7% of users.
* Instagram, Twitter, and Telegram each account for around 20% of users.
* The small differences in percentages indicate that no single platform dominates user preference in this dataset.

***Key Insight***

User preferences are fairly balanced across all social media platforms, suggesting that users are distributed almost equally among TikTok, Instagram, Twitter, Facebook, and Telegram. TikTok is the most preferred platform, but only by a small margin.
"""

#Which Social media platform is used the most
plt.pie(social_prefer,labels=social_prefer.index,autopct='%1.1f%%');
plt.title("Which Social Media Platform is most used by users")

print(social_prefer.max(), social_prefer.idxmax())

"""**What I Did**

Created a scatter plot to examine the relationship between daily social media usage and sleep duration.

***Libraries Used***
*Seaborn*
* sns.scatterplot() was used to create the scatter plot.
*Matplotlib*
* Used indirectly for displaying the visualization.
***Visualization Interpretation***
* The x-axis represents daily social media time (hours).
* The y-axis represents sleep hours per day.
* Most users spend between 0 and 8 hours on social media, while their sleep duration ranges from 3 to 10 hours.
* The points are widely scattered, indicating no strong relationship between social media usage and sleep hours.
* A few users spend more than 12 hours on social media, but their sleep patterns still vary considerably.

***Key Insight***

The scatter plot suggests that there is little to no clear correlation between daily social media usage and sleep duration in this dataset. People with both high and low social media usage appear to have a wide range of sleep hours, indicating that other factors may influence sleep patterns.
"""

sns.scatterplot(x='daily_social_media_time', y='sleep_hours',data=prod_df)

"""**What I Did**

Created a heatmap to analyze how perceived productivity scores vary across different age groups and social media platform preferences.

**Libraries Used**

***Pandas***

* pivot_table() was used to summarize the average perceived productivity score for each combination of age and social media platform.

***Seaborn***
* heatmap() was used to visualize the data using color intensity.
***Matplotlib***

* Used for figure sizing, labels, and title customization.

**Visualization Interpretation**

* The x-axis represents different social media platforms (Facebook, Instagram, Telegram, TikTok, Twitter).
* The y-axis represents age groups.
* The color intensity and values inside each cell represent the average perceived productivity score.
* Most productivity scores lie between 5.1 and 6.0, indicating relatively small variations across ages and platforms.
* No platform consistently shows significantly higher or lower productivity scores across all age groups.
* Some age-platform combinations have slightly higher scores (lighter shades), suggesting marginally better perceived productivity.

***Key Insight***

The heatmap indicates that perceived productivity remains fairly consistent across different social media platforms and age groups. While there are minor fluctuations, there is no strong evidence that a particular platform or age group is associated with substantially higher or lower perceived productivity in this dataset.
"""

plt.figure(figsize=(12,9))
df_pivot=prod_df.pivot_table(index='age',columns='social_platform_preference',values='perceived_productivity_score')
plt.yticks(rotation=75)
sns.heatmap(df_pivot,annot=True);
plt.title('Correlation between Social media Preferenceand Age with respect to perceived_productivity_score' )
plt.xlabel('Social Media Preference')
plt.ylabel('Age')

"""**What I Did**

Created a line chart to analyze how coffee consumption per day affects sleep hours and stress levels.

***Libraries Used***

*Seaborn*

* sns.lineplot() was used to plot the trends for sleep hours and stress level.
*Matplotlib*
* plt.legend() was used to label the lines.
* plt.title() was used to add a title to the chart.

**Visualization Interpretation**
* The x-axis represents coffee consumption per day.
* The y-axis represents the average values of sleep hours and stress level.
* Sleep hours remain relatively stable between 6 and 7 hours regardless of coffee consumption.
* Stress levels stay around 5 to 6 for most coffee consumption levels but increase noticeably at very high coffee consumption levels (9–10 cups per day).
* The sharp rise in stress level at higher coffee consumption suggests that excessive coffee intake may be associated with increased stress.

**Key Insight**

The graph indicates that moderate coffee consumption does not significantly affect sleep duration. However, individuals with very high coffee consumption tend to report higher stress levels. This suggests that excessive caffeine intake may contribute more to stress than to changes in sleeping hours.

**Conclusion**

Coffee consumption appears to have a weak relationship with sleep hours but a stronger relationship with stress levels at higher consumption levels. Most users maintain similar sleep durations, while stress tends to increase among heavy coffee consumers.
"""

sns.lineplot(x='coffee_consumption_per_day', y='sleep_hours', data=prod_df,marker='s')
sns.lineplot(x='coffee_consumption_per_day', y='stress_level', data=prod_df,marker='o')
plt.legend(['sleep_hours','stress_level'])
plt.title("How Coffee Consumption per day affects Sleeping hours and Stress Level")

"""**What I Did**

Calculated the average actual productivity score for each gender and displayed the results using a bar chart.

**Libraries Used**

***Pandas***

* groupby() was used to group data by gender.
* mean() was used to calculate the average productivity score.
sort_values() was used to sort the results.
*Matplotlib*
* plot(kind='bar') was used to create the bar chart.
* title(), xlabel(), and ylabel() were used to label the chart.
**Visualization Interpretation**
* The x-axis represents Gender (Female, Male, Other).
* The y-axis represents the Average Actual Productivity Score.
* The average productivity scores for all genders are very close, ranging between approximately 4.8 and 5.0.
* Female participants have the highest average productivity score.
* Male participants have a very similar average score.
* The Other category has a slightly lower average productivity score compared to the other two groups.

**Key Insight**

The chart suggests that gender has little impact on actual productivity scores in this dataset. Productivity levels are relatively consistent across all gender groups, with only minor differences in average scores.

**Conclusion**

There is no significant variation in productivity based on gender. All groups show similar productivity levels, indicating that factors other than gender may play a greater role in influencing productivity.
"""

platform_prod=prod_df.groupby('gender')['actual_productivity_score'].mean().sort_values(ascending=False)

platform_prod.plot(kind='bar',)
plt.title("Average Productivity Score by Gender")
plt.xlabel("Gender")
plt.ylabel("AverageProductivity Score")