# -*- coding: utf-8 -*-
"""Sales_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6BGPbb1ITWZ7IEdWzlNJOeSpYl7OQEx
"""

import pandas as pd
import numpy as np
df=pd.read_csv("ecommerce_sales_analysis.csv")

print(df.shape)
print(df.info())
print(df.describe())

print("-------------DATA CLEANING----------------------------")
print("------------Retreiving first 5 rows----------------------")
print(df.head())
print("--------------Retreiving last 5 rows----------------------")
print(df.tail())

print(df.isnull().sum())#no null values

print(df.duplicated().sum())#no duplicate values so need for drop_duplicates
print("------------------------------------------------------------------------")

print("---------------------------ADDING ADDITIONAL COLUMNS------------------------------")
sales_cols = [col for col in df.columns if 'sales_month_' in col]
df["total_sales"]   = df[sales_cols].sum(axis=1)
df["total_revenue"]=df["total_sales"]*df["price"]
#----------------BEST SELLING PRODUCTS-----------------------
print("-----------------TOP 5 best selling products by revenue-----------------------" )
top5_revenue=df.groupby("product_name")["total_revenue"].sum().sort_values(ascending=False).head()
print(top5_revenue)
print("----------------TOP 5 Best selling products by sales-----------------------")
top5_sales=df.groupby("product_name")["total_sales"].sum().sort_values(ascending=False).head()
print(top5_sales)
#----------------BEST SELLING PRODUCTS-----------------------
print("-----------------Best selling products by revenue-----------------------" )
max_revenue=df.groupby("product_name")["total_revenue"].sum().sort_values(ascending=False).max()
print(max_revenue)
print("----------------Best selling products by sales-----------------------")
max_sales=df.groupby("product_name")["total_sales"].sum().sort_values(ascending=False).max()
print(max_sales)
print("-----------MONTHLY SALES ANALYSIS--------------------")
monthly_sales=df[sales_cols].sum()
print(monthly_sales)
print("-------------Best sales by month-------------")
print(monthly_sales.idxmax(), "=", monthly_sales.max())

#------------------CATEGORY SALES ANALYSIS-------------------
print("---------------category sales analysis-------------")
category_revenue_series = df.groupby("category")["total_revenue"].sum().sort_values(ascending=False)
highest_revenue_category = category_revenue_series.index[0]
highest_revenue_value = category_revenue_series.iloc[0]
print(f"Highest revenue category: {highest_revenue_category}, Revenue: {highest_revenue_value}")

print("-------------- CUSTOMER PURCHASING ANALYSIS--------------")

customer_analysis = df.groupby("category").agg({
    "total_units": "sum",
    "review_score": "mean",
    "price": "mean"})

customer_analysis = customer_analysis.sort_values( by="total_units",ascending=False)
print(customer_analysis)

print("------------REVENUE ANALYSIS---------------")

revenue_analysis = df.groupby("category")["total_revenue"].sum()

revenue_analysis = revenue_analysis.sort_values(ascending=False)
print(revenue_analysis)
print("\nHighest Revenue Category:",revenue_analysis.idxmax())
print("Lowest Revenue Category:",revenue_analysis.idxmin())
print("\nTotal Revenue:",df["total_revenue"].sum())
print("\nAverage Revenue:",df["total_revenue"].mean())

df.to_csv("ecommerce_cleaned.csv", index=False)
print("\n✅ Clean file saved: ecommerce_cleaned.csv")